Updated for FRITZ-Dect 500 devices
kaklakariada/fritzbox-java-api pull request #16
Opened 2020-11-30 08:06 UTC by SmokingDevices

While playing around with this lib i noticed that some of the newer devices are not supported.

2020-12-02 16:14 UTC, kaklakariada requested changes

2020-12-02 16:14 UTC, kaklakariada commented on src/main/java/com/github/kaklakariada/fritzbox/mapping/Deserializer.java
> +        //LOG.info("parsing data:"+data);
Please don't add commented code
```suggestion
```

2020-12-02 16:14 UTC, kaklakariada commented on src/test/java/com/github/kaklakariada/fritzbox/mapping/DeserializerTest.java
> +        new Deserializer().parse(fileContent, DeviceList.class);
Thanks for adding tests 👍

2020-12-02 17:20 UTC, SmokingDevices commented on src/main/java/com/github/kaklakariada/fritzbox/mapping/Deserializer.java
> +        //LOG.info("parsing data:"+data);
has been removed, sorry for that.

2020-12-04 07:23 UTC, kaklakariada approved these changes

2020-12-04 07:23 UTC, merged

2020-12-04 07:24 UTC, kaklakariada commented
I will build a new release soon, maybe on the weekend.

2020-12-06 14:04 UTC, kaklakariada commented
Published 1.2.1 to jcenter: https://jcenter.bintray.com/com/github/kaklakariada/fritzbox-java-api/1.2.1/