Add support of empty device lists fixes #37
kaklakariada/fritzbox-java-api pull request #52
Opened 2022-08-09 05:49 UTC by TDesjardins

This pull request add empty device list support because this is an valid expected state if no smart home device is connected.

2022-08-09 15:59 UTC, kaklakariada approved these changes

2022-08-09 16:01 UTC, kaklakariada requested changes
Hi @TDesjardins,
thank you for your pull request! Please add a short entry to the changelog.

2022-08-09 17:01 UTC, TDesjardins commented
> Hi @TDesjardins, thank you for your pull request! Please add a short entry to the changelog.

Actually I don't see this in my responsibility because I don't know how do you plan releases and choose commits. I added an entry but this time is the last exception.

2022-08-10 17:32 UTC, kaklakariada approved these changes

2022-08-10 17:33 UTC, merged